### ISSUE TITLE
youtube not working anymore

### ISSUE THREAD

**Issue by ahmetsali** [pixel-industry/Social-Photo-Stream-jQuery-Plugin#3]
Hi, it seems to be youtube fetch not working anymore, any plan to fix this?

Thank you.

**Comment by pixel-industry** [comment]
Hi,

Yes, plugin will be updated this week.

Vladimir

**Comment by pixel-industry** [comment]
Hi,

I updated the plugin and Youtube is now working fine. You will need to obtain Youtube API key because plugin is fetching data through v3 API that requires API key.
