### ISSUE TITLE
Image Title Enhancement

### ISSUE THREAD

**Issue by asisten** [pixel-industry/Social-Photo-Stream-jQuery-Plugin#4]
Hello, I see that this plugins using filename as image title, how about to enhancement image title by removing dash and file extension?
for example:

`var photo_title = entry.title.replace(/.jpg/g, "").replace(/-/g, " ");`

will replace title like:
**my-best-photo.jpg**
into
**my best photo**

I think thats will be great esp for SEO purpose

**Comment by pixel-industry** [comment]
Sounds like a good idea. Update pushed.
