### ISSUE TITLE
Instagram widget not showing up ??

### ISSUE THREAD

**Issue by salmanunnao** [pixel-industry/Social-Photo-Stream-jQuery-Plugin#5]
Instagram widget suddenly disappeared.

**Comment by PhilJ88** [comment]
yes, same here

**Comment by pixel-industry** [comment]
Hi guys,

Yes, access_token should be updated as hourly rate limit is reached.

**Comment by kickblogger** [comment]
@pixel-industry That's the first thing i did. Still not working.

**Comment by kickblogger** [comment]
Yup, you need to update access_token. But it now fetches only your own media.

**Comment by pixel-industry** [comment]
@kickblogger Yes, unfortunately you can now fetch only your own media due to Instagram API changes.

Closing the issue.
